# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-20 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='deal_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='studentstudyrecord',
            unique_together=set([('student', 'classstudyrecord')]),
        ),
    ]
