# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-25 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20181120_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, '男'), (2, '女')], default=1, null=True),
        ),
    ]
