# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-25 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20181125_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
