# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-30 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20181125_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='class_list',
            field=models.ManyToManyField(blank=True, null=True, to='app01.ClassList', verbose_name='已报班级'),
        ),
    ]
